"""empty message

Revision ID: 0d9a4adf92b0
Revises: 7dcf1e317098
Create Date: 2022-07-01 18:15:54.241757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9a4adf92b0'
down_revision = '7dcf1e317098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admins_table_email', table_name='admins_table')
    op.create_index(op.f('ix_admins_table_email'), 'admins_table', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_table_email'), table_name='admins_table')
    op.create_index('ix_admins_table_email', 'admins_table', ['email'], unique=False)
    # ### end Alembic commands ###
