"""empty message

Revision ID: 7dcf1e317098
Revises: 12566b2ec349
Create Date: 2022-07-01 18:05:31.696532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dcf1e317098'
down_revision = '12566b2ec349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins_table', sa.Column('email', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_admins_table_email'), 'admins_table', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_table_email'), table_name='admins_table')
    op.drop_column('admins_table', 'email')
    # ### end Alembic commands ###
