"""empty message

Revision ID: 485ffc01d843
Revises: 8c5523f7c1e9
Create Date: 2022-07-01 16:33:57.934409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '485ffc01d843'
down_revision = '8c5523f7c1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('firstName', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=200), nullable=True),
    sa.Column('student_email', sa.String(length=200), nullable=True),
    sa.Column('matric_no', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_firstName'), 'students', ['firstName'], unique=False)
    op.create_index(op.f('ix_students_last_name'), 'students', ['last_name'], unique=False)
    op.create_index(op.f('ix_students_matric_no'), 'students', ['matric_no'], unique=False)
    op.add_column('Admins', sa.Column('firstName', sa.String(length=200), nullable=True))
    op.add_column('Admins', sa.Column('last_name', sa.String(length=200), nullable=True))
    op.add_column('Admins', sa.Column('password_hash', sa.String(length=200), nullable=False))
    op.create_index(op.f('ix_Admins_firstName'), 'Admins', ['firstName'], unique=False)
    op.create_index(op.f('ix_Admins_last_name'), 'Admins', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Admins_last_name'), table_name='Admins')
    op.drop_index(op.f('ix_Admins_firstName'), table_name='Admins')
    op.drop_column('Admins', 'password_hash')
    op.drop_column('Admins', 'last_name')
    op.drop_column('Admins', 'firstName')
    op.drop_index(op.f('ix_students_matric_no'), table_name='students')
    op.drop_index(op.f('ix_students_last_name'), table_name='students')
    op.drop_index(op.f('ix_students_firstName'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
