"""empty message

Revision ID: 6910676c8735
Revises: 3394ec961afc
Create Date: 2022-07-01 16:38:50.039286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6910676c8735'
down_revision = '3394ec961afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_students_matric_no', table_name='students')
    op.create_index(op.f('ix_students_matric_no'), 'students', ['matric_no'], unique=True)
    op.create_unique_constraint(None, 'students', ['student_email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_index(op.f('ix_students_matric_no'), table_name='students')
    op.create_index('ix_students_matric_no', 'students', ['matric_no'], unique=False)
    # ### end Alembic commands ###
