"""empty message

Revision ID: b316fb035349
Revises: 0d9a4adf92b0
Create Date: 2022-07-01 19:10:11.831068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b316fb035349'
down_revision = '0d9a4adf92b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('students', sa.Column('department', sa.String(length=64), nullable=True))
    op.add_column('students', sa.Column('level', sa.String(length=64), nullable=True))
    op.drop_constraint('students_student_email_key', 'students', type_='unique')
    op.create_index(op.f('ix_students_department'), 'students', ['department'], unique=False)
    op.create_index(op.f('ix_students_level'), 'students', ['level'], unique=False)
    op.create_unique_constraint(None, 'students', ['email'])
    op.drop_column('students', 'student_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('student_email', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_index(op.f('ix_students_level'), table_name='students')
    op.drop_index(op.f('ix_students_department'), table_name='students')
    op.create_unique_constraint('students_student_email_key', 'students', ['student_email'])
    op.drop_column('students', 'level')
    op.drop_column('students', 'department')
    op.drop_column('students', 'email')
    # ### end Alembic commands ###
