"""empty message

Revision ID: f88f4a57c2a4
Revises: 378d07ab9d4c
Create Date: 2022-07-01 17:51:07.798475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88f4a57c2a4'
down_revision = '378d07ab9d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('first_name', sa.String(length=200), nullable=True))
    op.drop_index('ix_admins_first_nam', table_name='admins')
    op.create_index(op.f('ix_admins_first_name'), 'admins', ['first_name'], unique=False)
    op.drop_column('admins', 'first_nam')
    op.add_column('students', sa.Column('first_name', sa.String(length=200), nullable=True))
    op.drop_index('ix_students_first_nam', table_name='students')
    op.create_index(op.f('ix_students_first_name'), 'students', ['first_name'], unique=False)
    op.drop_column('students', 'first_nam')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('first_nam', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_students_first_name'), table_name='students')
    op.create_index('ix_students_first_nam', 'students', ['first_nam'], unique=False)
    op.drop_column('students', 'first_name')
    op.add_column('admins', sa.Column('first_nam', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_admins_first_name'), table_name='admins')
    op.create_index('ix_admins_first_nam', 'admins', ['first_nam'], unique=False)
    op.drop_column('admins', 'first_name')
    # ### end Alembic commands ###
